import { ToolCategory, Tool, Badge } from "./types";

export const CATEGORIES: Record<string, ToolCategory> = {
  "content-creation": {
    id: "content-creation",
    name: "Creación de contenido",
    shortName: "CC",
    description: "Diseña infografías, presentaciones, posters multimedia y material interactivo.",
    colorClass: "bg-[#25A6E2] text-white",
    borderClass: "border-[#1D8AC0]",
    hoverClass: "hover:bg-[#1E95CE]",
    activeClass: "bg-[#25A6E2] text-white",
    textClass: "text-[#25A6E2]",
    gradientClass: "from-[#25A6E2]/20 to-[#25A6E2]/5",
    iconName: "Sparkles",
  },
  "assessment-gamification": {
    id: "assessment-gamification",
    name: "Evaluación y gamificación",
    shortName: "EG",
    description: "Cuestionarios interactivos, juegos competitivos, encuestas en vivo y retroalimentación.",
    colorClass: "bg-[#4CAF50] text-white",
    borderClass: "border-[#3E8E41]",
    hoverClass: "hover:bg-[#43A047]",
    activeClass: "bg-[#4CAF50] text-white",
    textClass: "text-[#4CAF50]",
    gradientClass: "from-[#4CAF50]/20 to-[#4CAF50]/5",
    iconName: "Trophy",
  },
  "collaboration-communication": {
    id: "collaboration-communication",
    name: "Comunicación y comunidad",
    shortName: "CM",
    description: "Herramientas para fomentar debates, trabajo en equipo y muros compartidos.",
    colorClass: "bg-[#00BCD4] text-white",
    borderClass: "border-[#0097A7]",
    hoverClass: "hover:bg-[#00ACC1]",
    activeClass: "bg-[#00BCD4] text-white",
    textClass: "text-[#00BCD4]",
    gradientClass: "from-[#00BCD4]/20 to-[#00BCD4]/5",
    iconName: "Users",
  },
  "visual-thinking": {
    id: "visual-thinking",
    name: "Organización de ideas y pizarrones",
    shortName: "OP",
    description: "Mapas conceptuales, pizarras digitales infinitas y tableros organizadores.",
    colorClass: "bg-[#FFEB3B] text-slate-900",
    borderClass: "border-[#FBC02D]",
    hoverClass: "hover:bg-[#FDD835]",
    activeClass: "bg-[#FFEB3B] text-slate-900",
    textClass: "text-[#FBC02D]",
    gradientClass: "from-[#FFEB3B]/20 to-[#FFEB3B]/5",
    iconName: "Palette",
  },
  "lms-management": {
    id: "lms-management",
    name: "Gestión de contenido",
    shortName: "GC",
    description: "Sistemas escolares centralizados (LMS), agendas, aulas digitales y portfolios.",
    colorClass: "bg-[#E91E63] text-white",
    borderClass: "border-[#C2185B]",
    hoverClass: "hover:bg-[#D81B60]",
    activeClass: "bg-[#E91E63] text-white",
    textClass: "text-[#E91E63]",
    gradientClass: "from-[#E91E63]/20 to-[#E91E63]/5",
    iconName: "Layers",
  },
  "educational-resources": {
    id: "educational-resources",
    name: "Contenido educativo",
    shortName: "CE",
    description: "Bancos de lecciones, videotutoriales, cursos autónomos y lecturas dirigidas.",
    colorClass: "bg-[#FF9800] text-white",
    borderClass: "border-[#F57C00]",
    hoverClass: "hover:bg-[#FB8C00]",
    activeClass: "bg-[#FF9800] text-white",
    textClass: "text-[#FF9800]",
    gradientClass: "from-[#FF9800]/20 to-[#FF9850]/5",
    iconName: "BookOpen",
  },
  "programming-coding": {
    id: "programming-coding",
    name: "Programación",
    shortName: "PR",
    description: "Aprende lógica espacial, codificación por bloques y desarrollo de videojuegos.",
    colorClass: "bg-[#FFC107] text-slate-900",
    borderClass: "border-[#FFA000]",
    hoverClass: "hover:bg-[#FFB300]",
    activeClass: "bg-[#FFC107] text-slate-900",
    textClass: "text-[#FFC107]",
    gradientClass: "from-[#FFC107]/20 to-[#FFC107]/5",
    iconName: "Terminal",
  },
  "productivity": {
    id: "productivity",
    name: "Herramientas y recursos",
    shortName: "HR",
    description: "Modelos de utilidad, PDFs, grabadores, extensiones y plantillas profesionales.",
    colorClass: "bg-[#3F51B5] text-white",
    borderClass: "border-[#303F9F]",
    hoverClass: "hover:bg-[#3949AB]",
    activeClass: "bg-[#3F51B5] text-white",
    textClass: "text-[#3F51B5]",
    gradientClass: "from-[#3F51B5]/20 to-[#3F51B5]/5",
    iconName: "ClipboardList",
  },
};

export const TOOLS: Tool[] = [
  // COLUMN 1: Content Creation (Bright Blue)
  {
    id: "genially",
    name: "Genially",
    symbol: "Ge",
    atomicNumber: 1,
    period: 1,
    group: 1,
    category: "content-creation",
    description: "Plataforma interactiva para crear presentaciones animadas, guías, infografías y juegos en equipo de alto impacto visual.",
    mainPedagogicalUse: "Ideal para gamificación y escape rooms interactivos que promueven el autoaprendizaje y la indagación guiada.",
    bestFor: ["Escape Rooms", "Presentaciones", "Infografías"],
    subjects: ["All Subjects", "Science", "History"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Crear un mapa interactivo para descubrir hitos históricos.", "Gamificar la evaluación diagnóstica de ciencias mediante un quiz temático."],
    officialWebsite: "https://www.genially.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "canva",
    name: "Canva",
    symbol: "Ca",
    atomicNumber: 2,
    period: 2,
    group: 1,
    category: "content-creation",
    description: "Herramienta de diseño gráfico accesible para crear posters, diapositivas, infografías pedagógicas y reportes interactivos.",
    mainPedagogicalUse: "Desarrollo de habilidades de síntesis visual, diseño de contenidos alineados y expresión gráfica innovadora por parte de estudiantes.",
    bestFor: ["Posters clase", "Presentaciones", "Flyers educativos"],
    subjects: ["Arts", "English", "Languages", "Science"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Diseñar posters grupales sobre especies en peligro de extinción.", "Estructurar la agenda semanal de clases con banners decorativos."],
    officialWebsite: "https://www.canva.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "piktochart",
    name: "Piktochart",
    symbol: "Pi",
    atomicNumber: 3,
    period: 3,
    group: 1,
    category: "content-creation",
    description: "Creador especializado de reportes de datos, infografías corporativas y material impreso formativo con gráficos interactivos.",
    mainPedagogicalUse: "Visualización clara de datos cuantitativos, reportes científicos e históricos y desarrollo de destrezas estéticas analíticas.",
    bestFor: ["Infografías de datos", "Reportes grupales", "Pósters de investigación"],
    subjects: ["Math", "Science", "Social Studies"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Resumir estadísticas de censos nacionales en infografías explicativas.", "Crear afiches de laboratorio integrando gráficas de temperatura en tiempo real."],
    officialWebsite: "https://www.piktochart.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "visme",
    name: "Visme",
    symbol: "Vs",
    atomicNumber: 4,
    period: 4,
    group: 1,
    category: "content-creation",
    description: "Editor de presentaciones dinámicas e infografías avanzadas con abundantes integraciones de audio y animaciones.",
    mainPedagogicalUse: "Enseñar narrativas multimedia estructuradas y diseño de micro-lecciones gamificadas autónomas.",
    bestFor: ["Diapositivas animadas", "Líneas de tiempo", "Micro-lecciones"],
    subjects: ["English", "History", "Business Education"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Desarrollar una línea de tiempo animada de la Revolución Industrial.", "Asignar un trabajo de mercadeo con gráficos interactivos animados."],
    officialWebsite: "https://www.visme.co",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "prezi",
    name: "Prezi",
    symbol: "Pz",
    atomicNumber: 5,
    period: 5,
    group: 1,
    category: "content-creation",
    description: "Software de presentaciones no lineales basado en zoom y transiciones espaciales dinámicas en un lienzo 2.5D interactivo.",
    mainPedagogicalUse: "Estructurar conceptos jerárquicos espaciales y mostrar relaciones complejas entre macro y micro estructuras.",
    bestFor: ["Lienzos espaciales", "Mapas mentales conceptuales", "Enfoques jerárquicos"],
    subjects: ["Science", "Geography", "Literature"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Explicar el sistema solar partiendo desde el macrocosmos hasta el núcleo planetario.", "Asignar una reseña coral de personajes literarios interconectados."],
    officialWebsite: "https://prezi.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "office-365",
    name: "Office 365",
    symbol: "Of",
    atomicNumber: 6,
    period: 6,
    group: 1,
    category: "content-creation",
    description: "Suite productiva estándar de Microsoft que incluye Word, PowerPoint, Excel, Teams y OneNote, ahora potenciados con herramientas colaborativas.",
    mainPedagogicalUse: "Colaboración escrita masiva concurrentemente, control de portafolios y modelamiento matemático estándar.",
    bestFor: ["Redacción de informes", "Diapositivas", "Control académico institucional"],
    subjects: ["All Subjects", "Technology"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Co-escribir un ensayo corporativo histórico en Word en vivo escolar.", "Catalogar valores de velocidad física experimental en tablas de Excel dinámicas."],
    officialWebsite: "https://www.office.com",
    priceModel: "Paid",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },

  // COLUMN 2: Content Creation extensions (Sky Blue)
  {
    id: "flipgrid",
    name: "Flipgrid",
    symbol: "Fg",
    atomicNumber: 7,
    period: 2,
    group: 2,
    category: "content-creation",
    description: "Plataforma de video-foros sociales donde los estudiantes responden en formato de micro-videos autograbados altamente personalizables.",
    mainPedagogicalUse: "Fomentar la expresión oral bilingüe, retroalimentación asíncrona entre pares, y democratización del debate en el aula.",
    bestFor: ["Práctica oral", "Vlogs escolares", "Retroalimentación asíncrona"],
    subjects: ["Languages", "English", "Arts", "Communications"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Grabar un análisis verbal crítico de un poema clásico de 2 minutos.", "Debatir asincrónicamente soluciones viables para minimizar plástico en el colegio."],
    officialWebsite: "https://info.flipgrid.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "nearpod",
    name: "Nearpod",
    symbol: "Np",
    atomicNumber: 8,
    period: 3,
    group: 2,
    category: "content-creation",
    description: "Sincroniza y dinamiza lecciones tradicionales adjuntando pizarras de dibujo interactivas, encuestas, modelos 3D y recorridos de realidad virtual.",
    mainPedagogicalUse: "Fomentar la gamificación formativa en vivo, comprobar conceptos mediante respuestas de dibujo directo y paseos en VR.",
    bestFor: ["Clases inmersivas", "Dibujos diagnósticos", "Flipped classroom"],
    subjects: ["History", "Science", "Math", "Geography"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Guiar un tour de realidad virtual en el Coliseo Romano pidiendo hipótesis estructurales.", "Evaluar aprendizaje espacial retando a dibujar parábolas matemáticas en vivo."],
    officialWebsite: "https://www.nearpod.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "powtoon",
    name: "PowToon",
    symbol: "Pt",
    atomicNumber: 9,
    period: 4,
    group: 2,
    category: "content-creation",
    description: "Generador de animaciones de caricaturas y videos explicativos profesionales con avatares preconfigurados y narración integrada.",
    mainPedagogicalUse: "Enseñanza de síntesis audiovisual creativa y fomento de exposiciones divertidas reduciendo ansiedad fonológica.",
    bestFor: ["Caricaturas explicativas", "Videos animados", "Narrativa visual"],
    subjects: ["Social Studies", "Science", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Explicar las 3 Leyes de Newton utilizando avatares animados cómicos.", "Asignar un trabajo de resumen del ciclo del agua adaptado para preescolares."],
    officialWebsite: "https://www.powtoon.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "goconqr",
    name: "GoConqr",
    symbol: "Gq",
    atomicNumber: 10,
    period: 5,
    group: 2,
    category: "content-creation",
    description: "Plataforma de recursos formativos que permite crear mapas globales de estudio, grupos de notas, tests modulares dinámicos y fichas mnemotécnicas.",
    mainPedagogicalUse: "Estructuración autónoma de lecciones individuales, entrenamiento de vocabulario mediante repetición espaciada o flashcards.",
    bestFor: ["Flashcards memorización", "Mapas relacionales", "Grupos de estudio"],
    subjects: ["Languages", "Medicine", "Social Studies"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Asignar tarjetas flashcards para memorizar conjugaciones verbales latinas.", "Crear mapas conceptuales detallados de la taxonomía del reino animalia."],
    officialWebsite: "https://www.goconqr.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "google-suite",
    name: "Google Suite",
    symbol: "Gs",
    atomicNumber: 11,
    period: 6,
    group: 2,
    category: "content-creation",
    description: "Conjunto colaborativo insignia basado en Google Drive, Docs, Sheets, Slides y Forms, integrados para una gestión de clase flexible y rápida.",
    mainPedagogicalUse: "Redacción colaborativa multijugador, co-autoría conceptual, y recopilación inmediata de formularios evaluativos.",
    bestFor: ["Docs cooperativos", "Almacenamiento en la nube", "Diapositivas compartidas"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Organizar una bitácora científica escolar mutua en un Google Doc público.", "Estructurar debates históricos creando slides colaborativas por equipos."],
    officialWebsite: "https://workspace.google.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: true,
  },

  // COLUMN 3: Content Creation tools part 3
  {
    id: "pixton",
    name: "Pixton",
    symbol: "Px",
    atomicNumber: 12,
    period: 4,
    group: 3,
    category: "content-creation",
    description: "Creador gráfico de cómics y tiras de caricaturas para diseñar historias adaptadas, diálogos de idiomas y recreaciones situacionales.",
    mainPedagogicalUse: "Práctica de habilidades comunicativas escritas, redacción de diálogos bilingües interactivos, y expresión creativa social.",
    bestFor: ["Tiras de cómics", "Historietas", "Diálogos de idiomas"],
    subjects: ["Languages", "English", "History", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Modelar una conversación cotidiana en francés mediante una tira cómica de 4 paneles.", "Recrear una emblemática escena histórica de la Revolución con diálogos originales."],
    officialWebsite: "https://www.pixton.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "emaze",
    name: "Emaze",
    symbol: "Ez",
    atomicNumber: 13,
    period: 5,
    group: 3,
    category: "content-creation",
    description: "Creador dinámico de sitios interactivos personalizados, galerías virtuales 3D de arte y lecciones conceptuales inmersivas.",
    mainPedagogicalUse: "Realización de paseos o galerías virtuales interactivas de arte y lecciones conceptuales inmersivas.",
    bestFor: ["Galerías 3D virtuales", "Presentaciones museos", "Páginas conceptuales"],
    subjects: ["Arts", "History", "Literature"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Alinear una exposición fotográfica virtual de pintura surrealista interactiva.", "Organizar presentaciones tridimensionales estimulantes sobre la arquitectura griega."],
    officialWebsite: "https://www.emaze.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "thinglink",
    name: "Thinglink",
    symbol: "Tl",
    atomicNumber: 14,
    period: 6,
    group: 3,
    category: "content-creation",
    description: "Herramienta especializada en añadir etiquetas numéricas, sonidos, textos y enlaces en imágenes planas 2D, panorámicas de 360° y mapas interactivos.",
    mainPedagogicalUse: "Análisis pormenorizado de esquemas complejos de anatomía, historia, ingeniería, y simulaciones geográficas interactivas.",
    bestFor: ["Imágenes interactivas", "Esquemas anatómicos", "Tours de geografía"],
    subjects: ["Science", "Geography", "History", "Arts"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Etiquetar partes del cerebro humano en una foto de súper alta resolución.", "Diseñar una lección inmersiva 360 dentro de las ruinas de Chichén Itzá con desafíos."],
    officialWebsite: "https://www.thinglink.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "flipsnack",
    name: "Flipsnack",
    symbol: "Fs",
    atomicNumber: 15,
    period: 6,
    group: 4,
    category: "content-creation",
    description: "Excelente convertidor y editor de folletos, revistas o PDFs escolares planos a libros interactivos con animación de pase de página real.",
    mainPedagogicalUse: "Publicación de periódicos escolares creados colaborativamente, revistas científicas estudiantiles y catálogos de proyectos.",
    bestFor: ["Revistas escolares", "Formatos PDF editores", "Lanzamientos de antologías"],
    subjects: ["English", "Languages", "Arts", "History"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Compilar poemas originales redactados por el grado en una antología digital.", "Publicar el periódico escolar semestral con reportajes enriquecidos con hipervínculos."],
    officialWebsite: "https://www.flipsnack.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },

  // COLUMN 4: Comunicación y Comunidad (Cyan)
  {
    id: "telegram",
    name: "Telegram",
    symbol: "Tg",
    atomicNumber: 16,
    period: 4,
    group: 4,
    category: "collaboration-communication",
    description: "Mensajería instantánea caracterizada por canales temáticos, bots educativos autoprogramables y cuestionarios interactivos nativos.",
    mainPedagogicalUse: "Envío seguro de avisos prioritarios institucionales, foros de consulta masivos y sondeos conceptuales relámpago.",
    bestFor: ["Canales informativos", "Bots autocorrectores", "Encuestas sencillas"],
    subjects: ["Other", "Communications", "Technology"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Programar cuestionarios de opción múltiple interactivos para autoaprendizaje.", "Gestionar un canal institucional de avisos y guías PDF rápidos para padres de familia."],
    officialWebsite: "https://telegram.org",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "slack",
    name: "Slack",
    symbol: "Sl",
    atomicNumber: 17,
    period: 4,
    group: 5,
    category: "collaboration-communication",
    description: "Espacio laboral para organizar debates mediante canales individuales de trabajo, integraciones y videoconferencias espontáneas.",
    mainPedagogicalUse: "Fomentar el trabajo cooperativo, la retroalimentación veloz en sub-equipos de proyecto, y la gestión de dudas centralizada.",
    bestFor: ["Trabajo grupal ágil", "Canales temáticos de discusión", "Integraciones bots"],
    subjects: ["Technology", "Business Education", "Higher Education"],
    educationLevel: ["Higher Education"],
    teachingScenarios: ["Crear canales (#ejercicios, #ayuda, #dudas) para dinamizar un taller universitario.", "Asignar canales privados a grupos de investigación para coordinar entregables de tesis."],
    officialWebsite: "https://slack.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "discord",
    name: "Discord",
    symbol: "Dc",
    atomicNumber: 18,
    period: 4,
    group: 6,
    category: "collaboration-communication",
    description: "Centralizador de comunidades de voz y texto organizado en servidores que resulta familiar para nativos digitales.",
    mainPedagogicalUse: "Aulas invertidas interactivas, tutorías integradoras basadas en canales de voz estables y foros informales guiados.",
    bestFor: ["Salas de chat por voz", "Comunidades estudiantiles virtuales", "Tutoría directa asíncrona"],
    subjects: ["Languages", "Technology", "All Subjects"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Configurar salas grupales de conversación oral de inglés abiertas 24/7.", "Implementar foros de discusión sobre dilemas filosóficos moderados por bots."],
    officialWebsite: "https://discord.com",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    symbol: "Tm",
    atomicNumber: 19,
    period: 5,
    group: 4,
    category: "collaboration-communication",
    description: "Herramienta integrada de videollamadas, chats institucionales orientados al aprendizaje, y flujo de tareas integradas de Office.",
    mainPedagogicalUse: "Salas de clases concurrentes en HD, estructuración de asignaciones remotas y almacenamiento en carpetas mutuas.",
    bestFor: ["Clases virtuales HD", "Tareas escolares integradas", "Mensajería oficial"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Programar clases semanales dividiendo los estudiantes en sub-salas de discusión remota.", "Evaluar entregas escritas y asignaciones usando la integración directa de rúbricas Teams."],
    officialWebsite: "https://www.microsoft.com/teams",
    priceModel: "Paid",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "classdojo",
    name: "ClassDojo",
    symbol: "Cd",
    atomicNumber: 20,
    period: 5,
    group: 5,
    category: "collaboration-communication",
    description: "Plataforma lúdica para comunicar familias y maestros, premiar comportamientos positivos mediante monstruos amigables personalizables.",
    mainPedagogicalUse: "Motivación e incentivo conductual temprano, control de hábitos diarios, y boletín en tiempo real para padres.",
    bestFor: ["Puntos de comportamiento lúdicos", "Boletines informativos padres", "Primaria y Preescolar"],
    subjects: ["Elementary Education", "Arts", "Other"],
    educationLevel: ["Elementary Education"],
    teachingScenarios: ["Otorgar insignias ('Excelente trabajo en equipo') a los perfiles de monstruo interactivos.", "Subir fotos de las clases de arte para mantener a las familias integradas en el proceso escolar."],
    officialWebsite: "https://www.classdojo.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "h5p",
    name: "H5P",
    symbol: "H5",
    atomicNumber: 21,
    period: 6,
    group: 5,
    category: "collaboration-communication",
    description: "Espectacular generador de elementos interactivos como videos autoexplicativos, resúmenes, dictados y cuestionarios incrustables.",
    mainPedagogicalUse: "Asegurar un rol activo de revisión, dictados auditivos autocorregibles, y contenido dinámico integrable en un LMS.",
    bestFor: ["Ensayos interactivos interactivos", "Contenido HTML5 interactivo", "Videos explicativos"],
    subjects: ["Languages", "Math", "Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Incrustar un video de física que detiene la reproducción para plantear opciones matemáticas obligatorias.", "Preparar dictados de francés autocorregibles para práctica de ortografía individual."],
    officialWebsite: "https://h5p.org",
    priceModel: "Free",
    difficulty: "Advanced",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },

  // COLUMN 5-6: Evaluación y Gamificación (Green)
  {
    id: "kahoot",
    name: "Kahoot!",
    symbol: "Kh",
    atomicNumber: 22,
    period: 4,
    group: 7,
    category: "assessment-gamification",
    description: "Cuestionarios de opción múltiple hiper-gamificados rápidos basados en tiempo real que despiertan la competitividad amigable.",
    mainPedagogicalUse: "Evaluación formativa rápida en vivo, repasos dinámicos pre-examen, e ideal como rompehielos lúdico.",
    bestFor: ["Quizzes veloces de trivia", "Evaluación formativa en vivo", "Participación total instantánea"],
    subjects: ["All Subjects", "Languages", "Math", "English"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Iniciar la clase con un quiz de 5 preguntas sobre la lectura asignada el día anterior.", "Asignar un Kahoot grupal para el repaso de conceptos biológicos complejos en equipo."],
    officialWebsite: "https://kahoot.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "edpuzzle",
    name: "Edpuzzle",
    symbol: "Ep",
    atomicNumber: 23,
    period: 4,
    group: 8,
    category: "assessment-gamification",
    description: "Excelente plataforma para convertir cualquier video web en una lección interactiva insertando notas de voz y quizzes evaluativos obligatorios.",
    mainPedagogicalUse: "Permite estructurar dinámicas de aprendizaje invertido (Flipped Classroom) garantizando rol activo al mirar videos curriculares.",
    bestFor: ["Aulas invertidas", "Comprobación videos interactivos", "Preguntas incrustables"],
    subjects: ["Science", "History", "Literature"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Pausar un documental biológico para evaluar si los alumnos reconocieron las mitocondrias de la célula.", "Asignar de tarea un video explicativo conceptual que registra las respuestas individuales de comprensión."],
    officialWebsite: "https://edpuzzle.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "quizizz",
    name: "Quizizz",
    symbol: "Qz",
    atomicNumber: 24,
    period: 4,
    group: 9,
    category: "assessment-gamification",
    description: "Cuestionarios motivadores con memes divertidos, retroalimentación instantánea, gamificados que se adaptan al ritmo individual del alumno.",
    mainPedagogicalUse: "Diagnósticos individuales sin frustración, exámenes diferenciados, tareas divertidas con tablas de lideres acumulativas.",
    bestFor: ["Exámenes sin presión", "Feedback personalizado memes", "Quizzes asíncronos en casa"],
    subjects: ["All Subjects", "Math", "Science"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Asignar un quiz lúdico sobre fracciones matemáticas con memes estimulantes.", "Habilitar un sondeo rápido diagnótico de inicio de trimestre de manera confidencial."],
    officialWebsite: "https://quizizz.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "classcraft",
    name: "Classcraft",
    symbol: "Cc",
    atomicNumber: 25,
    period: 5,
    group: 6,
    category: "assessment-gamification",
    description: "Transforma la experiencia de tu aula en un juego de rol RPG fantástico donde las misiones otorgan experiencia, salud y poderes cooperativos.",
    mainPedagogicalUse: "Motivación intrínseca escolar a largo plazo, ludificación extrema de la experiencia de clase y fomento de la cooperación sana.",
    bestFor: ["Juegos de rol ágiles", "Habilidades blandas conductuales", "Misiones cooperativas"],
    subjects: ["Other", "History", "Science"],
    educationLevel: ["Secondary Education"],
    teachingScenarios: ["Asignar misiones de rol donde curar compañeros depende del cumplimiento de tareas semanales.", "Otorgar puntos de experiencia XP de juego a equipos por debatir con respeto crítico."],
    officialWebsite: "https://www.classcraft.com",
    priceModel: "Freemium",
    difficulty: "Advanced",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "wordwall",
    name: "Wordwall",
    symbol: "Ww",
    atomicNumber: 26,
    period: 5,
    group: 7,
    category: "assessment-gamification",
    description: "Generador veloz de actividades variadas como sopas de letras, emparejamientos de términos, anagramas y ruedas del destino imprimibles.",
    mainPedagogicalUse: "Práctica sensorial, repaso acelerado de definiciones léxicas de manera ágil y motivadora.",
    bestFor: ["Rompecabezas de vocabulario", "Actividades sensoriales interactivas", "Fichas imprimibles rápidas"],
    subjects: ["Elementary Education", "Languages", "English", "Math"],
    educationLevel: ["Elementary Education"],
    teachingScenarios: ["Girar la 'Rueda de Participación Aleatoria' interactiva para seleccionar un alumno.", "Construir un juego interactivo de arrastrar palabras correspondientes a partes anatómicas de plantas."],
    officialWebsite: "https://wordwall.net",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "polleverywhere",
    name: "Poll Everywhere",
    symbol: "Pe",
    atomicNumber: 27,
    period: 5,
    group: 8,
    category: "assessment-gamification",
    description: "Sistema para recopilar opiniones de audiencias masivas en diapositivas enviando sus respuestas mediante SMS o páginas web al instante.",
    mainPedagogicalUse: "Sondear de manera anónima temas complejos de discusión ética, debates cívicos y evaluaciones diagnósticas inmediatas.",
    bestFor: ["Encuestas relámpago", "Debates anónimos masivos", "Retroalimentación en vivo"],
    subjects: ["Social Studies", "Higher Education", "Philosophy"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Lanzar un sondeo acerca de dilemas morales de economía en vivo en la pantalla general.", "Preguntar qué concepto teórico del examen se percibió más complejo para su inmediata retroalimentación."],
    officialWebsite: "https://www.polleverywhere.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "educaplay",
    name: "Educaplay",
    symbol: "Ec",
    atomicNumber: 28,
    period: 5,
    group: 9,
    category: "assessment-gamification",
    description: "Plataforma multi-actividades para confeccionar mapas interactivos para rellenar, crucigramas educativos, completados lingüísticos y dictados interactivos.",
    mainPedagogicalUse: "Clases asíncronas con autoevaluación integrada, memorización espacial lúdica de nombres e hitos geográficos.",
    bestFor: ["Crucigramas y mapas conceptuales", "Dictados bilingües interactivos", "Repaso asíncrono"],
    subjects: ["Languages", "Geography", "History", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Estructurar un mapa interactivo geográfico donde los chicos marcan capitales mundiales.", "Crear una sopa de letras interactiva sobre glándulas hormonales humanas para repasar en casa."],
    officialWebsite: "https://www.educaplay.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "plickers",
    name: "Plickers",
    symbol: "Pk",
    atomicNumber: 29,
    period: 5,
    group: 10,
    category: "assessment-gamification",
    description: "Fabulosa comprobación que recopila respuestas masivas mediante tarjetas impresas con códigos QR que el docente lee instantáneamente escaneando con la cámara de su celular.",
    mainPedagogicalUse: "Excelente para aulas analógicas o sin conectividad, sondeos formativos al instante en clases con limitaciones informáticas.",
    bestFor: ["Entornos analógicos sin conectividad", "Escaneo rápido códigos QR impresos", "Clase sin laptops individuales de alumnos"],
    subjects: ["All Subjects", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Evaluar la comprensión colectiva de un concepto matemático antes de proseguir, escaneando las tarjetas en 10 segundos.", "Sustituir las pizarras de borrado tradicionales de los niños por tarjetas de respuestas QR impresas."],
    officialWebsite: "https://plickers.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "liveworksheets",
    name: "Live Worksheets",
    symbol: "Lw",
    atomicNumber: 30,
    period: 6,
    group: 6,
    category: "assessment-gamification",
    description: "Integra tus folletos descargando PDFs clásicos y transfórmalos en hojas de ejercicios interactivas autoevaluables con audios y arrastrar-soltar.",
    mainPedagogicalUse: "Sustitución ecológica de fotocopias impresas tradicionales, adaptando de manera interactiva materiales antiguos con retroalimentación.",
    bestFor: ["Traducir PDFs planos a interactivos", "Ejercicios auditivos con audios integrados", "Redución de fotocopias"],
    subjects: ["Languages", "Elementary Education", "Special Education", "English"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Adaptar un folleto físico de lectura integrando casillas de verificación de comprensión.", "Configurar una sopa de letras interactiva de sustantivos arrastrados autocorregibles."],
    officialWebsite: "https://www.liveworksheets.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "mentimeter",
    name: "Mentimeter",
    symbol: "Mt",
    atomicNumber: 31,
    period: 6,
    group: 7,
    category: "assessment-gamification",
    description: "Especialista en recopilar opiniones de alumnos mediante nubes de palabras concurrentes, votaciones anónimas de conceptos y tests divertidos en vivo.",
    mainPedagogicalUse: "Estructurar evaluaciones diagnósticas inmediatas, registrar de forma anónima emociones complejas del aula y votaciones constructivas.",
    bestFor: ["Nubes de palabras en vivo", "Votos anónimos", "Recopilar perspectivas grupales"],
    subjects: ["Social Studies", "English", "Communications"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Generar una nube de sustantivos sobre 'Democracia' para debatir en vivo de inmediato en el aula.", "Preguntar confidencialmente y responder asertivamente dudas complejas al final de un capítulo científico."],
    officialWebsite: "https://www.mentimeter.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "pear-deck",
    name: "Pear Deck",
    symbol: "Pd",
    atomicNumber: 32,
    period: 6,
    group: 8,
    category: "assessment-gamification",
    description: "Complemento de alta utilidad para Google Slides que incrusta diapositivas con dibujos interactivos de alumnos en tiempo real de manera transparente.",
    mainPedagogicalUse: "Tener retroalimentación visual inmediata durante lecciones guiadas de matemáticas, ciencias o arte.",
    bestFor: ["Incrustar cuestionarios en Slides", "Respuestas de dibujo directas", "Lecciones en vivo controladas por docente"],
    subjects: ["Math", "Science", "History"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Colocar un círculo arrastrable pidiendo marcar en la pantalla el cloroplasto celular de manera individual.", "Alinear preguntas de conceptos que evalúan en vivo la absorción conceptual del grupo."],
    officialWebsite: "https://www.peardeck.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "socrative",
    name: "Socrative",
    symbol: "So",
    atomicNumber: 33,
    period: 6,
    group: 9,
    category: "assessment-gamification",
    description: "Simple y veloz evaluador con tests estándares en vivo, tickets de salida confidenciales rápidos y el divertido 'Space Race' competitivo por equipos.",
    mainPedagogicalUse: "Revisar la retención de datos empíricos de química o historia al instante de manera rápida con reportes estructurados.",
    bestFor: ["Competencia de Space Race", "Formularios de salida inmediatos", "Cuestionarios matemáticos estructurados"],
    subjects: ["Math", "Science", "Languages"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Correr un Space Race donde los chicos avanzan cohetes en pantalla resolviendo problemas químicos complejos.", "Mapear un veloz ticket de salida de 3 preguntas antes de concluir la sesión escolar diaria."],
    officialWebsite: "https://www.socrative.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "quizlet",
    name: "Quizlet",
    symbol: "Ql",
    atomicNumber: 34,
    period: 6,
    group: 10,
    category: "assessment-gamification",
    description: "Famoso repositorio de juegos con flashcards digitales interactivas, pronunciación directa de audios, y juegos lúdicos veloces.",
    mainPedagogicalUse: "Fomentar la memoria a largo plazo, entrenar vocabulario especializado de geografía o anatomía de manera independiente.",
    bestFor: ["Flashcards mnemotécnicas", "Entrenamiento de definiciones específicas", "Juegos de arrastre cronometrados"],
    subjects: ["Languages", "History", "Medical Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Repasar 50 términos anatómicos en latín mediante tarjetas digitales con auto-pronunciación activa.", "Dividir la clase en parejas para competir en el juego cronometrado de emparejar conceptos."],
    officialWebsite: "https://quizlet.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: true,
  },

  // COLUMN 7: Organización de Ideas & Pizarrones (Yellow)
  {
    id: "scratch",
    name: "Scratch",
    symbol: "Sc",
    atomicNumber: 35,
    period: 4,
    group: 10,
    category: "programming-coding",
    description: "Espacio creativo y entorno de programación visual por bloques que enseña lógica computacional creando juegos y animaciones interactivas.",
    mainPedagogicalUse: "Excelente para el pensamiento computacional intuitivo, demostración geométrica visual de variables y matemáticas aplicadas.",
    bestFor: ["Programación por bloques interactiva", "Juegos educativos infantiles", "Simular variables científicas"],
    subjects: ["Technology", "Math", "Science", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Programar una simulación del ciclo evolutivo animal animando los estados dentro de Scratch.", "Explicar coordenadas representadas por ejes X-Y animando un personaje saltarín dinámicamente."],
    officialWebsite: "https://scratch.mit.edu",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "padlet",
    name: "Padlet",
    symbol: "Pl",
    atomicNumber: 36,
    period: 4,
    group: 11,
    category: "visual-thinking",
    description: "Lienzo y tablero digital interactivo multiformato desarrollado para depositar notas, fotos conceptuales, grabaciones, esquemas y mapas.",
    mainPedagogicalUse: "Pizarra interactiva de brainstorming colectivo, paseos de galería estudiantiles y tableros cooperativos con comentarios cruzados.",
    bestFor: ["Muros de post-its interactivos", "Galerías o portafolios formativos grupales", "Recopilar de inmediato opiniones estructuradas"],
    subjects: ["English", "Languages", "Arts", "History"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Alinear un foro asíncrono escolar subiendo fotos y notas explicando hallazgos biológicos locales.", "Registrar opiniones iniciales sobre la guerra mediante notas conceptuales cruzadas."],
    officialWebsite: "https://padlet.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "jamboard",
    name: "Jamboard",
    symbol: "Jb",
    atomicNumber: 37,
    period: 4,
    group: 12,
    category: "visual-thinking",
    description: "Ligera y rápida pizarra cooperativa de Google, idónea para adjuntar post-its de colores, dibujar fluidamente y estructurar lluvias de ideas.",
    mainPedagogicalUse: "Intervenciones veloces concurrentemente durante debates virtuales y lecciones remotas.",
    bestFor: ["Lluvia de ideas concurrentes", "Clasificación veloz de notas de colores", "Dibujos rápidos matemáticos"],
    subjects: ["All Subjects", "Arts", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Reunir conceptos de redacción separándolos inmediatamente en notas clasificadas por colores de sustantivos.", "Resolver una ecuación física dibujando las fórmulas concurrentemente en pantalla mutua."],
    officialWebsite: "https://jamboard.google.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "hourofcode",
    name: "Hour of Code",
    symbol: "Hc",
    atomicNumber: 38,
    period: 5,
    group: 11,
    category: "programming-coding",
    description: "Campaña global que introduce la informática mediante tutoriales lúdicos asombrosos temáticos inspirados en Minecraft o Star Wars.",
    mainPedagogicalUse: "Ideales para eliminar el temor a las ciencias lógicas del cómputo integrando divertidas micro-misiones de bloque guiadas por personajes familiares.",
    bestFor: ["Gamificación STEM motivacional", "Cursos introductorios de informática", "Taller lógico de bloques rápidos"],
    subjects: ["Technology", "Math", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Participar en la 'Semana de la Informática' resolviendo misiones lógicas de Minecraft en equipos.", "Mapear divertidos laberintos lógicos geométricos aplicando principios de bucles condicionales."],
    officialWebsite: "https://hourofcode.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "explain-everything",
    name: "Explain Everything",
    symbol: "Ee",
    atomicNumber: 39,
    period: 5,
    group: 12,
    category: "visual-thinking",
    description: "Espectacular pizarra digital de nivel pro orientada a grabar lecciones en video explicativas con anotaciones en vivo y manipulación de formas.",
    mainPedagogicalUse: "Flipped classroom mediante grabación de micro-cápsulas teóricas de temas difíciles por parte del profesor y proyectos de video estudiantiles.",
    bestFor: ["Grabar micro-clases digitales asíncronas", "Ilustración interactiva fluida", "Presentaciones explicativas complejas"],
    subjects: ["Math", "Science", "Technology"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Grabar una resolución de álgebra trigonométrica detallando las operaciones paso a paso en video interactivo.", "Explicar conceptos físicos combinando manipulación de vectores virtuales con notas explicativas verbales."],
    officialWebsite: "https://explaineverything.com",
    priceModel: "Freemium",
    difficulty: "Advanced",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "mindmeister",
    name: "Mindmeister",
    symbol: "Mm",
    atomicNumber: 40,
    period: 5,
    group: 13,
    category: "visual-thinking",
    description: "Diseñe cooperativamente mapas conceptuales y esquemas conceptuales interactivos con jerarquías lógicas infinitas, hipervínculos organizados y archivos adjuntos.",
    mainPedagogicalUse: "Estructuración lógica de syllabus teóricos por equipos, catalogación ordenada de lecturas y organización de ideas previas a ensayos.",
    bestFor: ["Mapas conceptuales correlacionales interactivos", "Lluvia de ideas jerárquica", "Planificar ponencias"],
    subjects: ["Social Studies", "English", "Languages"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Diseñar colectivamente un mapa correlacional amplio con las causas de la Ilustración histórica.", "Catalogar ideas y citas textuales relevantes para elaborar un ensayo filosófico de trimestre."],
    officialWebsite: "https://www.mindmeister.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "app-inventor",
    name: "MIT App Inventor",
    symbol: "Ai",
    atomicNumber: 41,
    period: 6,
    group: 11,
    category: "programming-coding",
    description: "Plataforma web educativa del MIT para codificar de manera intuitiva por bloques aplicaciones funcionales reales listas para Android e iOS.",
    mainPedagogicalUse: "Creación de software con impacto comunitario, asimilando interfaces visuales de usuario, sensores y diseño ágil móvil.",
    bestFor: ["Creación directa de apps funcionales móviles", "Desarrollo lógico por bloques de nivel pro", "Mapear soluciones locales"],
    subjects: ["Technology", "Math", "Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Codificar una aplicación móvil que calcula la huella de carbono individual escolar.", "Desarrollar un prototipo de botón de auxilio rápido para los adultos mayores del barrio."],
    officialWebsite: "https://appinventor.mit.edu",
    priceModel: "Free",
    difficulty: "Advanced",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "trello",
    name: "Trello",
    symbol: "Tr",
    atomicNumber: 42,
    period: 6,
    group: 12,
    category: "visual-thinking",
    description: "Gestiona proyectos colaborativos mediante tableros kanban organizando entregas pendientes, en proceso, completadas con tarjetas detalladas.",
    mainPedagogicalUse: "Introducción a metodologías de trabajo ágiles, administración cooperativa de metas grupales complejas a largo plazo.",
    bestFor: ["Metodologías ágiles Kanban", "Coordinar proyectos amplios escolares de equipo", "Agenda escolar estructurada"],
    subjects: ["Technology", "All Subjects", "Business Education"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Distribuir tareas y fechas de entrega para el boletín escolar trimestral.", "Coordinar y guiar los hitos semanales del proyecto grupal de feria científica escolar."],
    officialWebsite: "https://trello.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "airtable",
    name: "Airtable",
    symbol: "At",
    atomicNumber: 43,
    period: 6,
    group: 13,
    category: "visual-thinking",
    description: "Fusión intuitiva entre una planilla de cálculo súper veloz similar a Google Sheets y una base de datos relacional robusta con vistas de galería e interfaces agradables.",
    mainPedagogicalUse: "Gestión avanzada de bases de datos relacionales científicas por alumnos, calendarios editoriales, y control estructurado de taxonomías.",
    bestFor: ["Bases de datos estructuradas relacionales de nivel pro", "Modelos de catálogo museos", "Inventarios escolares avanzados"],
    subjects: ["Technology", "Math", "Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Catalogar colectivamente insectos recolectados registrando fotos de muestra y coordenadas físicas.", "Gestionar un calendario editorial de proyectos periodísticos estructurado con fases de aprobación."],
    officialWebsite: "https://airtable.com",
    priceModel: "Freemium",
    difficulty: "Advanced",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },

  // ORANGE COLUMN / TOP right BLOCK: Contenido educativo (Orange)
  {
    id: "miro",
    name: "Miro",
    symbol: "Mr",
    atomicNumber: 44,
    period: 2,
    group: 14,
    category: "visual-thinking",
    description: "Lienzo y pizarra blanca cooperativa infinite diseñada de manera corporativa para crear complejos esquemas relacionales, diagramar y organizar lluvias de ideas.",
    mainPedagogicalUse: "Mapas mentales de amplias dimensiones jerárquicos de equipo, planeación compleja y metodologías visuales pro.",
    bestFor: ["Conceptualizaciones gigantes infinitas", "Muros de ideas integrados", "Lienzo de investigación cooperativo"],
    subjects: ["Technology", "Science", "Business Education"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Diagramar colectivamente el mapeo de procesos de un software informático.", "Planificar participaciones de debates grupales amplios separando argumentos de manera lógica."],
    officialWebsite: "https://miro.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "google-scholar",
    name: "Google Scholar",
    symbol: "Gs",
    atomicNumber: 45,
    period: 2,
    group: 15,
    category: "educational-resources",
    description: "Buscador especializado exclusivo en papers académicos revisados por pares científicos, tesis de grado doctrinales, citas estructuradas y patentes oficiales.",
    mainPedagogicalUse: "Enseñar el rigor académico estricto de investigación científica de grado, citación idónea normas APA e investigación verídica confiable.",
    bestFor: ["Investigaciones científicas APA", "Papers académicos filtrados", "Evidencia bibliográfica fidedigna"],
    subjects: ["All Subjects", "History", "Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Buscar 3 artículos sobre nanotecnología biomédica escolar redactando resúmenes.", "Validar y formalizar la procedencia bibliográfica de un ensayo de grado usando formato APA."],
    officialWebsite: "https://scholar.google.com",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "youtube",
    name: "YouTube",
    symbol: "Yt",
    atomicNumber: 46,
    period: 2,
    group: 16,
    category: "educational-resources",
    description: "El mayor repositorio gratuito global de contenido audiovisual educativo interactivo y recursos de creadores didácticos de ciencias.",
    mainPedagogicalUse: "Recursos complementarios e introductorios a temarios complejos de ciencias, repasos orales con soporte audiovisual.",
    bestFor: ["Recursos didácticos de video libre", "Taller de debate audiovisual", "Introducción estimulantes visuales"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Utilizar un video explicativo introductorio sobre agujeros de gusano antes de formular hipótesis.", "Recomendar playlists temáticos estructurados como apoyo remedial para alumnos con problemas conceptuales."],
    officialWebsite: "https://youtube.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "ted",
    name: "TED-Ed",
    symbol: "Td",
    atomicNumber: 47,
    period: 3,
    group: 14,
    category: "educational-resources",
    description: "Compendio de videos didácticos animados de alta producción sobre misterios del espacio, ciencia, literatura e historia acompañados de quizzes.",
    mainPedagogicalUse: "Hooks y detonadores de curiosidad científica amplios que estimulan el pensamiento lateral analítico y el debate institucional.",
    bestFor: ["Videos de alta calidad e interés", "Tópicos de debate interdisciplinar", "Preguntas de autoaprendizaje"],
    subjects: ["Science", "History", "Philosophy", "English"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Proyectar un video animado explicativo sobre la paradoja de Fermi pidiendo resúmenes.", "Asignar de tarea el quiz interactivo de un video del Antiguo Egipto con reporte directo de notas."],
    officialWebsite: "https://ed.ted.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "slideshare",
    name: "Slideshare",
    symbol: "Ss",
    atomicNumber: 48,
    period: 3,
    group: 15,
    category: "educational-resources",
    description: "Repositorio masivo para compartir de manera libre diapositivas curriculares, documentos técnicos PDFs estructurados e infografías elaboradas por docentes de todo el mundo.",
    mainPedagogicalUse: "Análisis veloz de materiales modulares curriculares existentes útiles de apoyo pedagógico directo y recopilación rápida de fuentes de consulta.",
    bestFor: ["Buscar presentaciones escolares", "Descarga de material de apoyo rápido", "Investigación bibliográfica visual"],
    subjects: ["All Subjects", "History", "Science"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Asignar la revisión crítica de 2 diapositivas sobre geografía física para extraer conceptos clave.", "Analizar esquemas sintéticos existentes para agilizar la preparación de clases de la semana."],
    officialWebsite: "https://www.slideshare.net",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "podcast",
    name: "Recursos Podcast",
    symbol: "Po",
    atomicNumber: 49,
    period: 3,
    group: 16,
    category: "educational-resources",
    description: "Plataforma integrada de archivos auditivos instructivos que promueven explicaciones narrativas detalladas del lenguaje o música.",
    mainPedagogicalUse: "Favorecer la comprensión auditiva analítica bilingüe, estimulación verbal imaginativa profunda y reducción de la fatiga en pantalla.",
    bestFor: ["Audio-lecciones detalladas comprensivas", "Educación auditiva asíncrona", "Análisis verbal oratorio"],
    subjects: ["Languages", "History", "Music"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Escuchar un fragmento asíncrono de podcast sobre el Descubrimiento debatiendo en la clase.", "Invitar a alumnos a estructurar y grabar su propio micro-podcast bilingüe explicativo escolar."],
    officialWebsite: "https://www.spotify.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "medium",
    name: "Medium Documentation",
    symbol: "Me",
    atomicNumber: 50,
    period: 4,
    group: 14,
    category: "educational-resources",
    description: "Lector y estructurador masivo de artículos escolares, noticias de tecnología, opiniones doctrinales e investigaciones de filosofía de nivel intermedio.",
    mainPedagogicalUse: "Incentivo a la lectura crítica en profundidad, escritura periodística escolar real y debate reflexivo ciudadano.",
    bestFor: ["Escritura de opinión periodística escolar", "Tópicos de actualidad e informática", "Lectura reflexiva profunda"],
    subjects: ["English", "Languages", "History", "Philosophy"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Publicar las reseñas críticas literarias escolares de alumnos en un blog colaborativo escolar real en Medium.", "Debatir grupalmente implicaciones técnicas de inteligencia artificial según expertos de Medium."],
    officialWebsite: "https://medium.com",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "khan-academy",
    name: "Khan Academy",
    symbol: "Ka",
    atomicNumber: 51,
    period: 4,
    group: 15,
    category: "educational-resources",
    description: "Plataforma insignia para la ejercitación matemática estructurada adaptada, lecciones de ciencias naturales y dashboards de progreso de maestría escolar.",
    mainPedagogicalUse: "Alivio y nivelación remedial, reforzamiento individual del currículum de matemáticas sin presiones y autoaprendizaje sistemático.",
    bestFor: ["Maestría estructurada de matemáticas", "Explicaciones algebraicas paso a paso", "Informes pormenorizados directos de docentes"],
    subjects: ["Math", "Science", "History"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Tener repasos algebraicos semanales asíncronos en casa progresando de forma autónoma.", "Mapear un refuerzo formativo adaptivo individualizado para alumnos desfasados del plan matemático escolar."],
    officialWebsite: "https://www.khanacademy.org",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "duolingo",
    name: "Duolingo",
    symbol: "Dl",
    atomicNumber: 52,
    period: 5,
    group: 15,
    category: "educational-resources",
    description: "Repetidor lingüístico lúdico enfocado en pronunciación bilingüe, conjugación espacial con racha de días retadores y retroalimentación inmediata.",
    mainPedagogicalUse: "Soporte interactivo entretenido para entrenar fonemas de otros idiomas y vocabulario temprano en niños de manera divertida.",
    bestFor: ["Vocabulario inicial interactivo", "Pronunciar de manera lúdica oraciones", "Rachas diarias divertidas académicas"],
    subjects: ["Languages"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Asignar 2 lecciones en Duolingo Classroom para fomentar hábito lingüístico de vocabulario cotidiano.", "Organizar competencias amistosas sumando puntos de racha en inglés escolar mensual."],
    officialWebsite: "https://www.duolingo.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "deepstash",
    name: "Deepstash",
    symbol: "Ds",
    atomicNumber: 53,
    period: 6,
    group: 14,
    category: "educational-resources",
    description: "Catalogador de micro-ideas, resúmenes concretos de libros populares de superación, liderazgo, ciencias y negocios ordenados en fichas sencillas.",
    mainPedagogicalUse: "Fomentar la lectura ágil, el auto-liderazgo escolar y sintetización ágil de ideas fundamentales.",
    bestFor: ["Síntesis de ideas y resúmenes ágiles", "Auto-liderazgo estudiantil", "Fichas mnemotécnicas directas de conceptos"],
    subjects: ["English", "Other", "Philosophy"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Inspirar discusiones semanales de auto-liderazgo compartiendo tarjetas motivacionales explicativas de Deepstash.", "Sintetizar metas académicas escribiendo fichas breves en bitácoras grupales estudiantiles."],
    officialWebsite: "https://deepstash.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },

  // RED ROW 7: Gestión de Contenido / LMS (Red)
  {
    id: "google-classroom",
    name: "Google Classroom",
    symbol: "Gc",
    atomicNumber: 54,
    period: 7,
    group: 1,
    category: "lms-management",
    description: "Espacio escolar y aula digital para asignar tareas interactivas, dar feedback directo, calificar transparentemente y publicar avisos oficiales sin papeles.",
    mainPedagogicalUse: "Gestión centralizada del aula remota y presencial, asignación ágil de recursos virtuales y comunicación estructurada directa con padres.",
    bestFor: ["Entregar tareas sin imprimir", "Portafolios interactivos organizadores", "Calendario escolar centralizado"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Organizar módulos semanales con guías de estudio, lecturas y formularios interconectados.", "Calificar trabajos cooperativos adjuntando comentarios constructivos inline de forma transparente."],
    officialWebsite: "https://classroom.google.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "moodle",
    name: "Moodle LMS",
    symbol: "Md",
    atomicNumber: 55,
    period: 7,
    group: 2,
    category: "lms-management",
    description: "Sistema académico open-source flexible para crear cursos estructurados con condicionalidades, foros calificados de debate y rúbricas altamente complejas.",
    mainPedagogicalUse: "Diseñar aulas invertidas, impartir exámenes diagnósticos altamente robustos en línea e incentivar discusiones por hilos estructuradas.",
    bestFor: ["Cursos robustos adaptivos", "Exámenes seguros en línea con banco de ítems", "Rúbricas complejas directas"],
    subjects: ["All Subjects", "Technology"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Configurar un examen de cálculo donde desbloquear el examen final requiera notas elevadas en lecciones previas.", "Gestionar foros de discusión formales científicos evaluados según una rúbrica estructurada nativa."],
    officialWebsite: "https://moodle.org",
    priceModel: "Free",
    difficulty: "Advanced",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "exelearning",
    name: "eXeLearning",
    symbol: "Ex",
    atomicNumber: 56,
    period: 7,
    group: 3,
    category: "lms-management",
    description: "Creador libre de contenidos educativos digitales que permite generar unidades de aprendizaje exportables en SCORM e integrables en Moodle de forma fácil.",
    mainPedagogicalUse: "Edición escolar modular descargable de recursos de indagación, adaptando contenidos interactivos sin dominar programación compleja.",
    bestFor: ["Creación de lecciones SCORM", "Integración Moodle directa", "Diseño interactivo modular offline"],
    subjects: ["Technology", "All Subjects"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Compilar un libro dinámico sobre geografía física listo para incrustarlo en Moodle escolar.", "Generar cuestionarios diagnósticos interactivos exportables integrados en planes de clase autónomos."],
    officialWebsite: "https://exelearning.net",
    priceModel: "Free",
    difficulty: "Advanced",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "symbaloo",
    name: "Symbaloo",
    symbol: "Sy",
    atomicNumber: 57,
    period: 7,
    group: 4,
    category: "lms-management",
    description: "Tablero interactivo de marcadores y botones organizados de forma visual para agrupar todas las aplicaciones, recursos y páginas web en un mapa idóneo.",
    mainPedagogicalUse: "Curaduría visual de fuentes de información libre de ruidos para estudiantes que minimizan el extravío cibernético escolar.",
    bestFor: ["Curación visual de links de consulta", "Páginas del docente recomendadas", "Minimizar clicks distractores"],
    subjects: ["All Subjects", "Elementary Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Crear un panel temático de marcadores web recomendados para investigar el calentamiento global de manera guiada.", "Reunir todas las plataformas lúdicas de inglés de primaria en un mapa intuitivo de botones visuales."],
    officialWebsite: "https://www.symbaloo.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "wordpress",
    name: "Wordpress",
    symbol: "Wp",
    atomicNumber: 58,
    period: 7,
    group: 5,
    category: "lms-management",
    description: "El creador global de blogs y páginas informativas más robusto que permite publicar portfolios interactivos, bitácoras escolares de alto alcance investigativo.",
    mainPedagogicalUse: "Creación de periódicos de indagación grupales reales, portfolios escolares científicos interactivos que potencian escritura pro.",
    bestFor: ["Publicar portafolios escolares de nivel pro", "Blogs y revistas escolares de indagación real", "Desarrollar webs interactivas estudiantiles"],
    subjects: ["English", "Languages", "History", "Technology"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Publicar boletines históricos mensuales sobre investigaciones cívicas redactadas en equipo.", "Implementar el portafolio final de tesis de grado estudiantil organizado con categorías estructuradas."],
    officialWebsite: "https://wordpress.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "blogger",
    name: "Blogger",
    symbol: "Bl",
    atomicNumber: 59,
    period: 7,
    group: 6,
    category: "lms-management",
    description: "Sencillo e histórico servicio de creación de bitácoras en red creado por Google que permite redactar opiniones públicas sin configuraciones difíciles.",
    mainPedagogicalUse: "Iniciar bitácoras de geografía tempranas individuales y redactar crónicas de opinión escolar semanales.",
    bestFor: ["Bitácoras escolares individuales y fáciles", "Ejercicios breves literarios públicos", "Aulas virtuales de opinión"],
    subjects: ["English", "Languages", "History"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Registrar crónicas periódicas de viajes de campo escolares subiendo evidencias fotográficas.", "Compartir pequeños ensayos cortos interpretativos analizando corrientes poéticas clásicas."],
    officialWebsite: "https://www.blogger.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "google-sites",
    name: "Google Sites",
    symbol: "Gs",
    atomicNumber: 60,
    period: 7,
    group: 7,
    category: "lms-management",
    description: "Creador ágil de portales de internet integrado estrechamente con Drive que facilita armar espacios temáticos explicativos en minutos sin código.",
    mainPedagogicalUse: "Creación ágil de portafolios de trabajo, compilación integral del centro de asignaciones escolare y diarios digitales.",
    bestFor: ["Portafolios ágiles Drive integrados", "Syllabus interactivo web", "Proyectos de internet veloces en equipo"],
    subjects: ["All Subjects", "Technology"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Diseñar en equipo el portal con los hallazgos experimentales de física aplicada del grado.", "Construir de manera ágil el cronograma institucional anual con asignaciones detalladas."],
    officialWebsite: "https://sites.google.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "notion",
    name: "Notion Education",
    symbol: "No",
    atomicNumber: 61,
    period: 7,
    group: 8,
    category: "lms-management",
    description: "Workspace modular para construir bitácoras conceptuales interactivas, bases de datos, agendas, cronogramas de estudios adaptados y lecciones.",
    mainPedagogicalUse: "Personal lesson planner, estructurador pro de portafolios académicos para universitarios, y wikis de equipo ágiles.",
    bestFor: ["Wikis de trabajo de equipo sumamente flexibles", "Estrecha agenda estructurada modular", "Modelos de syllabus pro"],
    subjects: ["English", "Science", "Technology", "All Subjects"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Preparar una base de datos interactiva ordenando referencias bibliográficas conjuntas.", "Coordinar y resumir todas las tareas escolares pendientes asignadas al grupo de tesis en Notion."],
    officialWebsite: "https://www.notion.so",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "edmodo",
    name: "Edmodo Platform",
    symbol: "Ed",
    atomicNumber: 62,
    period: 7,
    group: 9,
    category: "lms-management",
    description: "Red y entorno seguro estructurado similar a Facebook que emula un foro de debate de clase interactivo con encuestas institucionales y control.",
    mainPedagogicalUse: "Foros formativos preliminares seguros de debates, foros informales asíncronos y asimilación de comportamientos digitales idóneos.",
    bestFor: ["Foros parecidos a redes sociales familiares", "Paseo de comentarios escolares seguros", "Asignación ágil asíncrona"],
    subjects: ["Social Studies", "English", "Languages"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Publicar dilemas éticos planteando opiniones respetuosas concurrentemente entre alumnos.", "Sugerir debates informales de opinión literaria sobre la obra analizada de la semana."],
    officialWebsite: "https://www.edmodo.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: true,
  },
  {
    id: "wakelet",
    name: "Wakelet",
    symbol: "Wk",
    atomicNumber: 63,
    period: 7,
    group: 10,
    category: "lms-management",
    description: "Excelente y visual curador de lecciones que agrupa enlaces didácticos, tweets de interés, videos explicativos y PDFs, presentándolos hermosamente.",
    mainPedagogicalUse: "Asignar de manera ordenada las lecturas iniciales de lección, colecciones conjuntas de material curricular sin distracciones.",
    bestFor: ["Curador conceptual visual de links", "Diarios de bitácora modular agrupada", "Control visual de material didáctico"],
    subjects: ["All Subjects", "History", "Geography"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Reunir boletines científicos, podcasts e informes sobre misiones planetarias en una sola cartelera interactiva.", "Asignar un trabajo colaborativo para curar la evidencia fotográfica de una salida de campo de geología."],
    officialWebsite: "https://wakelet.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "scoopit",
    name: "Scoop.it",
    symbol: "Sc",
    atomicNumber: 64,
    period: 7,
    group: 11,
    category: "lms-management",
    description: "Buscador especializado y agregador de noticias temáticas de vanguardia que reúne novedades de prensa del área que configures.",
    mainPedagogicalUse: "Estudios científicos modernos enfocados en coyunturas de actualidad internacional, medicina emergente y curaduría selectiva.",
    bestFor: ["Investigar actualidad económica internacional", "Recopilar material e informes novedosos", "Debates institucionales contemporáneos"],
    subjects: ["Social Studies", "Science", "Business Education"],
    educationLevel: ["Higher Education"],
    teachingScenarios: ["Reunir reportajes y papers de biotecnología aplicada publicándolos en un boletín de clase.", "Debatir el desarrollo de energías renovables analizando notas filtradas concurrentemente por scoop.it."],
    officialWebsite: "https://www.scoop.it",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },

  // VIOLET ROW 8: Herramientas y Recursos (Violet / Productivity category identifier)
  {
    id: "multimedia",
    name: "Herramientas Multimedia",
    symbol: "Mu",
    atomicNumber: 65,
    period: 8,
    group: 1,
    category: "productivity",
    description: "Grabación y edición modular de audio y video (como Audacity o Clipchamp) ideales para audiolibros, explicaciones orales y cápsulas educativas.",
    mainPedagogicalUse: "Grabación de explicaciones orales breves, audiolibros y podcasts educativos creados por el grupo.",
    bestFor: ["Videos breves", "Clips formativos de audio", "Narrativa digital"],
    subjects: ["Communications", "Languages", "Arts"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Grabar audio de cuentos clásicos creados por alumnos de preescolar.", "Editar un mini documental biográfico de interés local científico."],
    officialWebsite: "https://www.audacityteam.org",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "pdf",
    name: "Utilidades PDF",
    symbol: "Pd",
    atomicNumber: 66,
    period: 8,
    group: 2,
    category: "productivity",
    description: "Fusores y compresores rápidos de documentos virtuales (como IlovePDF) que facilitan la optimización y distribución impresa cómoda.",
    mainPedagogicalUse: "Organización y reducción de peso en materiales curriculares densos, liberando recursos didácticos comprimidos sin fallos de lectura.",
    bestFor: ["Comprimir folletos masivos", "Unir lecturas curriculares PDF", "Dividir guías escolares"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Unir 3 lecturas científicas complementarias en un solo archivo PDF unificado.", "Liberar guías de ejercicios escolares con pesos ligeros para facilitar descarga en smartphones."],
    officialWebsite: "https://www.ilovepdf.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "gestion-archivos",
    name: "Gestión de Archivos",
    symbol: "Ga",
    atomicNumber: 67,
    period: 8,
    group: 3,
    category: "productivity",
    description: "Almacenamiento y catalogadores en la nube (como Dropbox, OneDrive o Box) que permiten organizar carpetas de trabajos gigantes escolares.",
    mainPedagogicalUse: "Organizar repositorios estables escolares transparentemente accesibles de material formativo histórico.",
    bestFor: ["Carpetas masivas compartidas", "Control de versiones de lecciones", "Resguardar evidencias"],
    subjects: ["All Subjects"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Mantener una carpeta histórica de evidencias experimentales de olimpiadas de física.", "Sincronizar y respaldar todas las guías en formato PDF por trimestres escolares."],
    officialWebsite: "https://www.dropbox.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "conferencias",
    name: "Videoconferencias",
    symbol: "Cf",
    atomicNumber: 68,
    period: 8,
    group: 4,
    category: "productivity",
    description: "Entornos estables de videollamadas académicas virtuales remotas (como Zoom, Skype, Google Meet) que unifican pantallas y clases de apoyo.",
    mainPedagogicalUse: "Impartir clases maestras a la distancia, tutorías de apoyo uno a uno confidenciales e invitaciones a oradores extranjeros.",
    bestFor: ["Clases remotas masivas", "Tutoría de refuerzo escolar directo", "Llamadas intercolegiales"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Conectarse de inmediato con un científico extranjero para una sesión de preguntas y respuestas.", "Conducir tutorías virtuales personalizadas de repaso de geometría pre-examen."],
    officialWebsite: "https://zoom.us",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: true,
    isAssessment: false,
  },
  {
    id: "plantillas",
    name: "Plantillas Curriculares",
    symbol: "Pl",
    atomicNumber: 69,
    period: 8,
    group: 5,
    category: "productivity",
    description: "Modelos estructurados de syllabus formativos, bitácoras escolares de autoaprendizaje, rúbricas de evaluación listas para duplicarse en clase.",
    mainPedagogicalUse: "Sustentación de metodologías integradoras estables reduciendo fricción burocrática al planificar lecciones pedagógicas.",
    bestFor: ["Planificar lecciones veloces", "Rúbricas preconfiguradas", "Agendas didácticas estables"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Utilizar un modelo preconfigurado de planeación didáctica por competencias.", "Compartir una rúbrica lista de autoevaluación cooperativa con el área escolar."],
    officialWebsite: "https://www.slidesgo.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: true,
  },
  {
    id: "extensiones",
    name: "Extensiones del Navegador",
    symbol: "Ex",
    atomicNumber: 70,
    period: 8,
    group: 6,
    category: "productivity",
    description: "Pequeños aditamentos del explorador web chrome que capturan pantallas, leen textos con pronunciación fonética y analizan citas en segundos.",
    mainPedagogicalUse: "Garantizar una lectura inclusiva mediante asistentes lectores de texto auditivos para alumnos disléxicos o con baja visión.",
    bestFor: ["Captura de evidencias veloces", "Lectores de pantalla auditivos inclusivos", "Optimización de búsquedas"],
    subjects: ["Technology", "Languages", "Special Education"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Asistir a alumnos con dificultades de lectura habilitando el lector automático de textos auditivo.", "Recolectar capturas explicativas de ejemplos físicos en Internet para bitácoras escolares."],
    officialWebsite: "https://chromewebstore.google.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "seguridad",
    name: "Protección y Seguridad",
    symbol: "Sg",
    atomicNumber: 71,
    period: 8,
    group: 7,
    category: "productivity",
    description: "Filtros de control reflexivos con antivirus educativos y antivirus (como Malwarebytes) que bloquean publicidad maliciosa distractora escolar.",
    mainPedagogicalUse: "Establecer entornos reflexivos cibernéticos idóneos libres de peligros cibernéticos y anuncios pornográficos/pesados.",
    bestFor: ["Navegación escolar libre de ruidos", "Filtro de seguridad malwarebytes", "Privacidad informática obligatoria"],
    subjects: ["Technology", "Other"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Instalar bloqueadores robustos de anuncios de video en equipos del aula escolar interactiva.", "Configurar credenciales seguras de acceso para los alumnos protegiendo la identidad escolar."],
    officialWebsite: "https://www.malwarebytes.com",
    priceModel: "Freemium",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "creacion-avatars",
    name: "Creación de Avatars",
    symbol: "Av",
    atomicNumber: 72,
    period: 8,
    group: 8,
    category: "productivity",
    description: "Generadores visuales de personajes interactivos con estilos variados (como Bitmoji), dotando de mayor identidad digital a los foros.",
    mainPedagogicalUse: "Resguardo y protección de la identidad visual física de los menores de edad utilizando un alter-ego virtual interactivo confidencial.",
    bestFor: ["Proteger rostros e identidad física", "Símbolos decorativos interactivos de perfiles", "Roles cívicos virtuales"],
    subjects: ["Arts", "Elementary Education", "Special Education"],
    educationLevel: ["Elementary Education", "Secondary Education"],
    teachingScenarios: ["Retar a menores de edad a crear su clon en ilustración Bitmoji para sus entregas digitales.", "Enmascarar participantes de un debate sensible de comportamiento utilizando su avatar personalizado de equipo."],
    officialWebsite: "https://www.bitmoji.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "bancos-imagenes",
    name: "Bancos de Imágenes",
    symbol: "Bi",
    atomicNumber: 73,
    period: 8,
    group: 9,
    category: "productivity",
    description: "Bancos y repositorios fotográficos sin regalías en altísima resolución (como Unsplash o Pixabay) con licencias CC0 útiles para asambleas.",
    mainPedagogicalUse: "Enseñanza y modelamiento del respeto a los derechos de autor intelectuales y uso lícito de recursos audiovisuales.",
    bestFor: ["Encontrar fotos HD sin regalías de autor", "Soporte de diapositivas estéticas", "Proyectos escolares gráficos"],
    subjects: ["Arts", "Languages", "All Subjects"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Incentivar el uso de bases de fotos con licencia abierta de autor para informes de olimpiadas de historia.", "Seleccionar retratos estéticos representativos de países hispanos para ilustrar resúmenes culturales."],
    officialWebsite: "https://unsplash.com",
    priceModel: "Free",
    difficulty: "Beginner",
    isAiPowered: false,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "bancos-ilustraciones",
    name: "Bancos de Ilustraciones",
    symbol: "Bs",
    atomicNumber: 74,
    period: 8,
    group: 10,
    category: "productivity",
    description: "Compendio de vectores libres, diagramas artísticos explicativos e iconos estáticos modernos (como Freepik o Undraw) que elevan el nivel estético.",
    mainPedagogicalUse: "Elección y modelamiento estético visual refinado, optimizando las diapositivas del docente con recursos de calidad pro.",
    bestFor: ["Ilustraciones vectoriales modernas libres", "Esquematizar diapositivas estimulantes", "Iconos vectorizaciones"],
    subjects: ["Arts", "Technology", "Business Education"],
    educationLevel: ["Secondary Education", "Higher Education"],
    teachingScenarios: ["Descargar iconos vectorizados representativos de ciencias para ilustrar el temario de clases.", "Crear una presentación institucional integrando ilustraciones minimalistas uniformes en su diseño."],
    officialWebsite: "https://www.freepik.com",
    priceModel: "Freemium",
    difficulty: "Beginner",
    isAiPowered: true,
    isCollaborative: false,
    isAssessment: false,
  },
  {
    id: "comunidades-educativas",
    name: "Comunidades Educativas",
    symbol: "Ce",
    atomicNumber: 75,
    period: 8,
    group: 11,
    category: "productivity",
    description: "Agrupaciones y redes mundiales de docentes de vanguardia tecnológica, donde asimilar lecciones exitosas y debatir tendencias formativas.",
    mainPedagogicalUse: "Formación profesional contínua interactiva, co-creación internacional interdisciplinaria escolar y soporte técnico pedagógico mutuo.",
    bestFor: ["Redes docentes cibernéticas", "Saber tendencias formativas internacionales", "Encontrar lecciones preparadas"],
    subjects: ["All Subjects"],
    educationLevel: ["Elementary Education", "Secondary Education", "Higher Education"],
    teachingScenarios: ["Debatir la asimilación responsable escolar de Inteligencia Artificial Generativa con colegios aliados.", "Encontrar planes e ideas de lecciones de física del agua probadas exitosamente en otros colegios."],
    officialWebsite: "https://www.microsoft.com/education",
    priceModel: "Free",
    difficulty: "Intermediate",
    isAiPowered: false,
    isCollaborative: true,
    isAssessment: false,
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: "onboarding-badge",
    name: "Pionero Digital",
    description: "Completaste el Test de Diagnóstico de Inicio y creaste tu portafolio de docente innovador.",
    iconName: "Compass",
    unlockedAt: null,
    xpValue: 100,
  },
  {
    id: "explore-all-cc",
    name: "Creador de Contenido",
    description: "Exploraste las herramientas insignias de Creación de Contenido interactivo (Canva o Genially).",
    iconName: "Sparkles",
    unlockedAt: null,
    categoryRequirement: "content-creation",
    xpValue: 150,
  },
  {
    id: "gamification-badge",
    name: "Maestro de Evaluación",
    description: "Revisaste 3 o más herramientas lúdicas de Evaluación y Gamification formativa.",
    iconName: "Trophy",
    unlockedAt: null,
    categoryRequirement: "assessment-gamification",
    countRequirement: 3,
    xpValue: 200,
  },
  {
    id: "collaboration-badge",
    name: "Fomentador de Sinergias",
    description: "Descubriste 3 o más herramientas de Comunicación y Comunidad escolar.",
    iconName: "Users",
    unlockedAt: null,
    categoryRequirement: "collaboration-communication",
    countRequirement: 3,
    xpValue: 200,
  },
  {
    id: "superstar-badge",
    name: "Explorador del Ecosistema",
    description: "Exploraste 15 o más herramientas dentro de la Gran Tabla de Docentes.",
    iconName: "Globe",
    unlockedAt: null,
    countRequirement: 15,
    xpValue: 500,
  },
  {
    id: "daily-badge",
    name: "Curiosidad Insaciable",
    description: "Reclamaste tu bonificación de XP de descubrimiento diario hoy.",
    iconName: "Flame",
    unlockedAt: null,
    xpValue: 120,
  }
];

export const DAILY_WORDS_OF_WISDOM = [
  "¡La programación con Scratch en lenguas estimula la creatividad lingüística! Gamifica historias de vocabulario hoy.",
  "Flipgrid permite que hasta el chico más tímido tenga una voz clara en evaluaciones asíncronas orales.",
  "Divide actividades asíncronas difíciles construyendo pequeños quizzes lúdicos interactivos en Edpuzzle.",
  "Usa Jamboard o Padlet para recopilar dudas confidenciales durante clases multitudinarias presenciales.",
  "Unifica todos tus recursos didácticos de Chrome en un Symbaloo limpio para evitar distracciones tontas en proyecciones."
];
